#!/bin/sh

echo "[post-commit hook] Commit done!"

# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty

# Find out if this is a smart commit (e.g. git commit -m "JQWE-123 #time 1h #comment fixed it" will log 1 hour already)
commit_message=$(git log -1 HEAD)
if [[ "$commit_message" == *"#time"* ]]; then
  is_smart_commit=true
else
  is_smart_commit=false
fi

# Ask for JIRA credentials and store the base64 encoded version of what the user enters
parse_jira_credentials() {
  read -p "Please enter your jira username and password like this: username:password " credentials
  jira_credentials=$(printf "$credentials" | base64)
  echo "$jira_credentials" > "$jira_credentials_file" 
}

# Parse the git branch
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

# Parse the JIRA ticket in the branch
parse_jira_ticket_in_branch() {
  parse_git_branch | grep -e '[A-Z]\+-[0-9]\+' -o
}

# Read JIRA credentials if they exist (no shame in useless cat, this is my first bash script!)
jira_credentials_file=".git/hooks/jira_credentials.txt"

if [ -e "$jira_credentials_file" ]; then
  jira_credentials=$(cat "$jira_credentials_file")
else
  parse_jira_credentials
fi

if [ "$is_smart_commit" = false ]; then
  read -p "[post-commit hook] How long did that take to do? (e.g. 1d 2h 30m) " time
  if [ "$time" = "" ]; then
    exit
  else
    ticket=`parse_jira_ticket_in_branch`
    response=$(eval curl "-D- --write-out %{http_code} --silent --output /dev/null -X POST -d '{\"timeSpent\":\"$time\"}' -H 'Authorization: Basic $jira_credentials' -H 'Content-Type: application/json' https://thrillistmediagroup.atlassian.net/rest/api/2/issue/\"$ticket\"/worklog")
    if [[ $response =~ "201 Created" ]]; then
      echo "[post-commit hook] $time successfully logged to $ticket!"
    elif [[ $response =~ "401 Unauthorized" ]]; then
      read -p "[post-commit hook] $time was not logged successfully to $ticket. If you have updated your credentials in JIRA, press 'u' to update them here so that this hook works on your next commit. Otherwise, hit enter to ignore. " option
      if [[ $option == "u" ]]; then
        parse_jira_credentials
      else
        exit
      fi
    else
      echo "Not sure"
    fi
    exit
  fi
else
  exit
fi
